name: CI 🧪
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 16.x

      - name: Install Dependencies 
        run: pnpm install

      - name: Build
        working-directory: ./generator
        run: pnpm build
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
